### ISSUE TITLE
Security exception while scanning locations which we don't want our tests to access

### ISSUE THREAD

**Issue by trejkaz** [lukehutch/fast-classpath-scanner#104]
We're trying to integrate this into our tests where the security manager has been locked down to stop people accessing files they should not need to access.

When scanning, we get this exception:

    java.security.AccessControlException: access denied ("java.io.FilePermission" "/System/Library/Java/jre/lib/rt.jar" "read")
    	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
    	at java.security.AccessController.checkPermission(AccessController.java:884)
    	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
    	at java.io.File.exists(File.java:814)
    	at io.github.lukehutch.fastclasspathscanner.utils.JarUtils.isJREJar(JarUtils.java:78)
    	at io.github.lukehutch.fastclasspathscanner.utils.JarUtils.isJREJar(JarUtils.java:118)
    	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathRelativePath.isValidClasspathElement(ClasspathRelativePath.java:345)
    	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$1.processWorkUnit(Scanner.java:252)
    	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$1.processWorkUnit(Scanner.java:242)
    	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:133)
    	... 6 more

This is coming from the code which is supposed to determine whether a given jar belongs to the JRE.

            final File parent = file.getParentFile();
            if (parent == null) {
                return false;
            }
            final String parentPathStr = parent.getPath();
            if (knownJREPaths.contains(parentPathStr)) {
                return true;
            }
            if (knownNonJREPaths.contains(parentPathStr)) {
                return false;
            }
            File rt = new File(parent, File.separatorChar == '/' ? "jre/lib/rt.jar"
                    : String.format("jre%clib%crt.jar", File.separatorChar, File.separatorChar));
            boolean rtExists;
            if (!(rtExists = rt.exists())) {       // 👈  error from this call
                rt = new File(parent, File.separatorChar == '/' ? "lib/rt.jar"
                        : String.format("lib%crt.jar", File.separatorChar));
                if (!(rtExists = rt.exists())) {
                    rt = new File(parent, "rt.jar");
                    rtExists = rt.exists();
                }
            }

In my particular case, the file it's trying to test is /System/Library/Java/Extensions/AppleScriptEngine.jar - so in this case, not part of the JDK, but a system extension that seems be shipped with the OS. (Which is funny, actually. I swear Apple stopped supporting Java, but here it is, AppleScriptEngine.jar on OS 10.12, in the System location...)

In any case, `File.exists()` can throw `SecurityException`, which should be handled more gracefully than this.

In this particular case, though, I feel like simply checking whether the JAR is inside the location designated by `"java.home"` (maybe also `"java.ext.dirs"`?) might be a simpler method of determining this, rather than looking for rt.jar. I know that earlier versions of the JDK on macOS didn't have rt.jar at all, but rather divided the code into several jars. Java 9 is probably not going to have it either...

**Comment by trejkaz** [comment]
Ah, slight correction:

When file = /System/Library/Java/Extensions/AppleScriptEngine.jar , our policy seems to let it through, because we do allow reading from anywhere in java.ext.dirs.

When file = /System/Library/Java/Extensions , it causes the problem, because it gets
rt = /System/Library/Java/jre/lib/rt.jar , which is not inside a location we allow reading from, thus raising SecurityException.

I guess for some annoying reason, Java on macOS allows people to put classes directly into that extensions dir instead of packaging them in jars.

**Comment by lukehutch** [comment]
@trejkaz thanks for this report. I had no idea that `File#exists()` could throw an exception! I fixed all usages of that method in the codebase.

Good thought on `java.home` and `java.ext.dirs`. I'll add those as the preferred means of locating the JRE. It will actually speed up scanning a lot to not have to search the neighborhood directories of each jar to determine if it's a system jar or not.

The only thing is, is it always guaranteed that at least `java.home` will be defined? I was under the impression that Java can still run if it is undefined (or at least, if the `JAVA_HOME` environment variable is not defined).

How is `java.home` set? Is it just read directly from the `JAVA_HOME` environment variable, or is it derived from the location of the `java` binary?

**Comment by trejkaz** [comment]
In terms of how it (Oracle JVM) actually sets it itself, it _probably_ figures it out based on the location of the JVM library being loaded, or . Because at least on Windows, it's possible for the executable you run to be in System32, but you still get the value for the actual version you ended up running.

Other implementations are probably free to do it however they want, i.e. it's probably undefined. JRockIt and IBM set the same thing though, from memory. The contents of the directory it specifies are probably undefined also.

I don't know whether it _must_ be present in any JVM, but I do know that the security manager can deny access to read the property, in which case you would get a `SecurityException` from the `getProperty` call as well.

**Comment by lukehutch** [comment]
@trejkaz the SecurityExceptions are hopefully all caught now (also for path canonicalization).

Thanks for the info on other JREs. I know that in Fedora's OpenJDK, the packages and binaries have been split into weird locations in the past too.

I figure that your suggestion is probably the best way to handle this in general though, so I made the change in the most recent patch.

Can you please test the git master version, and let me know if it works for you? (Note that I also added Java info near the top of the verbose log output, you can check that if you want to see what JRE resources were found.)  Thanks!

**Comment by lukehutch** [comment]
Released in 2.0.12, please let me know if this solves your problem.

**Comment by trejkaz** [comment]
Back at work now, retested on 2.0.12, looks good to me. Thanks!

**Comment by lukehutch** [comment]
@trejkaz Great, thanks for testing, and thanks for the report.
