### ISSUE TITLE
Stale cached data in Fast-classpath-scanner

### ISSUE THREAD

**Issue by jaredjstewart** [lukehutch/fast-classpath-scanner#109]
I am running into an issue where it seems that fast-classpath-scanner is caching some data that causes it to fail when used multiple times.  Here is the code using fast-classpath-scanner:

```
  private List<String> findFunctionsInThisJar(File jarFile) throws IOException {
    URLClassLoader urlClassLoader = new URLClassLoader(new URL[]{jarFile.getCanonicalFile().toURL()});
    FastClasspathScanner fastClasspathScanner =
        new FastClasspathScanner().removeTemporaryFilesAfterScan(true).overrideClassLoaders(urlClassLoader);
    ScanResult scanResult = fastClasspathScanner.scan();
    return scanResult.getNamesOfClassesImplementing(Function.class);
  }
```

I thought that this ought to avoid caching issues, since I am creating a new FastClasspathScanner each time and am making sure to override the classloaders to only consider the one jar I'm interested in.  Here is the exception I am running into:

```
java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /private/var/folders/v0/q5cmgqrj3ps1cm8g24nkbgbh0000gp/T/junit266545420653548100/server-2
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1115)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1143)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1166)
	at org.apache.geode.internal.DeployedJar.findFunctionsInThisJar(DeployedJar.java:341)
	at org.apache.geode.internal.DeployedJar.loadClassesAndRegisterFunctions(DeployedJar.java:189)
	at org.apache.geode.internal.JarDeployer.registerNewVersions(JarDeployer.java:449)
	at org.apache.geode.internal.JarDeployer.deploy(JarDeployer.java:489)
	at org.apache.geode.management.internal.cli.functions.DeployFunction.execute(DeployFunction.java:68)
	at org.apache.geode.internal.cache.MemberFunctionStreamingMessage.process(MemberFunctionStreamingMessage.java:191)
	at org.apache.geode.distributed.internal.DistributionMessage.scheduleAction(DistributionMessage.java:376)
	at org.apache.geode.distributed.internal.DistributionMessage$1.run(DistributionMessage.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.geode.distributed.internal.DistributionManager.runUntilShutdown(DistributionManager.java:621)
	at org.apache.geode.distributed.internal.DistributionManager$9$1.run(DistributionManager.java:1067)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /private/var/folders/v0/q5cmgqrj3ps1cm8g24nkbgbh0000gp/T/junit266545420653548100/server-2
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:217)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:61)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /private/var/folders/v0/q5cmgqrj3ps1cm8g24nkbgbh0000gp/T/junit266545420653548100/server-2
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:876)
	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:215)
	... 5 more
``` 

(Note that I have JUnit test with two test methods.  Both of them pass in isolation.  But I get this exception when running the whole test class.  The NoSuchFileException occurs in the second test method, and refers to a stale path that was used by and then deleted by the first test method.)  Do you see anything I am doing that stands out as incorrect?  Thank you!

**Comment by lukehutch** [comment]
@jaredjstewart interesting. Repeat scanning should not be an issue here per se, because the lifecycle of lists of internally-created temporary files is bound to the lifecycle of a scan, using `AutoCloseable` ([[1]](https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/Scanner.java#L209), [[2]](https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/utils/NestedJarHandler.java#L257)). However, can you please confirm if in the version you are running, the line Scanner.java:217 refers to this?:

```java
currentdirPath = FastPathResolver.resolve(Paths.get("").toAbsolutePath().normalize()
        .toRealPath(LinkOption.NOFOLLOW_LINKS).toString());
```

If so, something else is happening here: sometime after the creation of the temporary directory (`/private/var/folders/v0/q5cmgqrj3ps1cm8g24nkbgbh0000gp/T/junit266545420653548100/server-2`), something changes the current directory to that temporary directory. Then at the end of the first scan, the directory is removed -- but that doesn't change the current directory setting. So when FastClasspathScanner tries to resolve the path `""` (a reference to the current directory), it fails.

FastClasspathScanner does not change the current directory anywhere, at least intentionally. Is your code potentially setting the current directory?

One way to test this is to set the current directory to your home directory right before you call `fastClasspathScanner.scan()`. Does that fix the problem?

A couple of things:

* `.removeTemporaryFilesAfterScan(true)` is the default (i.e. this is not needed)
* I appreciate that this is an isolated test (thanks for the minimal testcase), but note that providing your own classloader can introduce problems with having multiple instances of a class loaded by different classloaders, or the superclass loaded by one classloader and a subclass by another, preventing casting, etc.

**Comment by jaredjstewart** [comment]
Thank you for the excellent feedback.  The "user.dir" property was indeed being modified at runtime, and removing that code fixed the problem.

**Comment by lukehutch** [comment]
@jaredjstewart Great, thanks for testing, and for reporting back!
