### ISSUE TITLE
NPE during class load

### ISSUE THREAD

**Issue by deepueg** [lukehutch/fast-classpath-scanner#112]
Throws an NPE while trying to use this in one of my android projects. 

```
java.lang.NullPointerException: Attempt to get length of null array
at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathFinder.findAllClassLoaders(ClasspathFinder.java:234)
at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.<init>(ScanSpec.java:432)
at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.getScanSpec(FastClasspathScanner.java:138)
at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.matchSubclassesOf(FastClasspathScanner.java:670)
```

Here is the code snippet that I am executing 

```
 new FastClasspathScanner().matchSubclassesOf(MyClass.class, new SubclassMatchProcessor<MyClass>() {
            @Override
            public void processMatch(Class<? extends MyClass> subclass) {
                Logger.e("Scanner", "Found subclass for MyClass: " + subclass);
            }
        }).scan();
```

**Comment by lukehutch** [comment]
Hi, can you please call  `.verbose()` before `.scan()`, and attach the log here?

**Comment by deepueg** [comment]
I am seeing the same logs with verbose as well!.

**Comment by lukehutch** [comment]
@deepueg I see, I just committed a fix for the NPE, thank for the report. However, FastClasspathScanner is untested with Dalvik, see #24 . I would be curious as to whether this is the only fix that is needed to get FCS working with Android, or if more changes are needed -- please let me know. Thanks!

**Comment by deepueg** [comment]
Thanks for the quick fix! I will try and let you know!

**Comment by deepueg** [comment]
```E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.sample.app.test, PID: 10851
                                                   java.lang.RuntimeException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                                                       at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1408)
                                                       at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1439)
                                                       at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1462)

                                                       at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                       at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Paths;
                                                       at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:217)
                                                       at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:59)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.Paths" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.sample.app.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sample.app.test-1/lib/x86, /data/app/com.sample.app.test-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:217) 
                                                       at io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:59) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                       at java.lang.Thread.run(Thread.java:761) ```

**Comment by lukehutch** [comment]
This is strange -- `Paths` has been around since Java 1.7, but is it not included in Android? It's very strange that the absence of this class is not caught at build/link time.

The code that throws this exception is:

```java
                Path currDirPath = Paths.get("").toAbsolutePath();
```

Can you please see if you can get a regular Android project to compile and run with this code (i.e. regular Java code in a project that is not linked in from classfiles via Maven)?

**Comment by lukehutch** [comment]
@deepueg it looks like `java.nio.*` was incomplete prior to Android O. Can you please try with the Android O developer preview? 

[https://developer.android.com/reference/java/nio/file/Paths.html](https://developer.android.com/reference/java/nio/file/Paths.html)

I will also work to make this class optional, by using reflection.

**Comment by lukehutch** [comment]
Oh, and of course I wasn't thinking about this carefully enough, because even if this problem is solved, the Dalvik classfile format is completely different from the Java classfile format, and the runtime classpath doesn't even really exist in Android, as described in #24. FastClasspathScanner reads the bytecode format directly, so even if the `Paths` problem is solved for Android versions before O, FCS simply cannot parse Dalvik yet. It will take a lot of work to get FCS working with Dalvik, too, since the DEX format is complex: https://source.android.com/devices/tech/dalvik/dex-format  An alternative might be to use baksmali: https://github.com/JesusFreke/smali

For now, I'll close this, since #24 covers the underlying issue, that Dalvik is not yet supported. (Sorry about that -- patches welcome.)

**Comment by deepueg** [comment]
@lukehutch I will try to spend more time later on this when I get a chance.! thanks for your help!.
