### ISSUE TITLE
Need  MethodParameters in MethodInfo

### ISSUE THREAD

**Issue by dantesun** [lukehutch/fast-classpath-scanner#147]
io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser skips all the method attributes. But "MethodParameters" is a new method attribute introduced in JDK8 which can be used in many senarios. Please consider adding "MethodParameters" in MethodInfo

**Comment by lukehutch** [comment]
Thanks for the request. ([Spec ref](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.24))

Do you need the final/synthetic/mandated flag, or just the method parameter names?

**Comment by lukehutch** [comment]
@GedMarc I see your thumbs-up above -- please feel free to answer the above question too. Thanks!
/cc @dantesun

**Comment by lukehutch** [comment]
I just added a patch for method names. (I don't yet have the final/synthetic/mandated flag available, since I'm not sure how useful it will be..)

**Comment by dantesun** [comment]
@lukehutch thanks for the quick fix. I tried the latest code from master branch. here is the error:

`2017-10-23T01:46:06.671+0800	FastClasspathScanner	-- Exception in worker thread
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- java.lang.ArrayIndexOutOfBoundsException: 2048
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.getConstantPoolStringOffset(ClassfileBinaryParser.java:278)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.getConstantPoolString(ClassfileBinaryParser.java:309)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ClassfileBinaryParser.readClassInfoFromClassfileHeader(ClassfileBinaryParser.java:862)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElement.parseClassfiles(ClasspathElement.java:271)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$5.processWorkUnit(Scanner.java:426)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.Scanner$5.processWorkUnit(Scanner.java:420)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue.runWorkLoop(WorkQueue.java:133)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue$1.call(WorkQueue.java:99)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.utils.WorkQueue$1.call(WorkQueue.java:96)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-10-23T01:46:06.671+0800	FastClasspathScanner	---- 	at java.lang.Thread.run(Thread.java:745)`

Unfortunately I can't upload the .class file causing this error because it's from our company's private code base.

**Comment by lukehutch** [comment]
@dantesun thanks, will take a look later today. Please see my earlier question -- do you need the parameter type flag?

**Comment by lukehutch** [comment]
@dantesun Should be fixed now, can you please test again? Sorry that it wasn't working when I committed the code, I hadn't had a chance to write the unit test yet!

**Comment by lukehutch** [comment]
Worth noting -- the method parameter names are only stored in the classfile if the `-parameters` switch is used on the commandline when the code is compiled.

**Comment by lukehutch** [comment]
@dantesun also, I can't duplicate the `java.lang.RuntimeException: Unreleased instances: 1`. This says that the program tried to shut down (due to exception) while one `ZipFile` was still open. This should not have happened, and I can't duplicate it. I looked through the code to try to determine how this is happening, and can't see where a race condition could arise (all the worker threads should be shut down when an exception is thrown, then all the ZipFiles closed, then the ZipFile recycler freed). I know you can't share the classfile with me, but do you have a simple test project that you could share, that demonstrates the problem? (It may be hard to duplicate, because it is probably a race condition.) PS you will need to test on the older version of the code that you tried before, not the latest master version (which no longer throws the original exception you reported). Thanks!

**Comment by dantesun** [comment]
I assume MethodInfo.getParameterTypeStr would work. What I really need is having a full method signature (return type, method name, parameter type/name/index)  without actually loading the class.

**Comment by lukehutch** [comment]
@dantesun OK, I just added the parameter names to `MethodInfo#toString()`. I also added support for the parameter type flags (final/synthetic/mandated), so those will show up in the parameter types as modifiers, if the flags are set. Please let me know if this works for you.

PS please see my previous comment about `java.lang.RuntimeException: Unreleased instances: 1`, I would like to debug that too, so that FCS shuts down cleanly on exception. I have not come across that issue before. You could duplicate this using the master version of the code, by inserting a `throw new RuntimeException("bombed")` in the same block that was throwing before (before line 871 of `ClassfileBinaryParser.java`, in the block that starts with `} else if (constantPoolStringEquals(attributeNameCpIdx, "MethodParameters")) {`.)  Are you able to get this working with a small test project that doesn't contain your company's proprietary code? Thanks!

**Comment by lukehutch** [comment]
@dantesun Method parameter support is included in release 2.7.5 of FastClasspathScanner. Thank you for this feature request!  /cc @GedMarc

(Also, I found and fixed the race condition in the resource release process when an exception was triggered -- thanks for the stacktrace that led to me finding that.)
