### ISSUE TITLE
Match Processor Exception

### ISSUE THREAD

**Issue by GedMarc** [lukehutch/fast-classpath-scanner#212]
Hey Luke!

Sooo, i'm guessing I need to expose something for a process exception?

JDK 10.0.1

Exception creating Injector : Multiple exceptions thrown of type: java.lang.NullPointerException. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().io.github.lukehutch.fastclasspathscanner.MatchProcessorException: Multiple exceptions thrown of type: java.lang.NullPointerException. To see individual exceptions, call MatchProcessorException#getExceptions(), or call FastClasspathScanner#verbose() before FastClasspathScanner#scan().
	at io.github.lukehutch.fastclasspathscanner@3.1.10/io.github.lukehutch.fastclasspathscanner.MatchProcessorException.newInstance(MatchProcessorException.java:92)

**Comment by lukehutch** [comment]
Hi @GedMarc -- did you try calling the method this exception suggests? That will let you get all the individual exceptions, then you can call their printStackTrace() method to see what happened and where.

**Comment by GedMarc** [comment]
mmm

Caused by: java.lang.NullPointerException
	at io.github.lukehutch.fastclasspathscanner@3.1.10/io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:359)
	at io.github.lukehutch.fastclasspathscanner@3.1.10/io.github.lukehutch.fastclasspathscanner.scanner.Scanner.call(Scanner.java:58)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
 - [SEVERE]

**Comment by GedMarc** [comment]
scanner.verbose(true);
		scanner.createClassLoaderForMatchingClasses();

		registerScanQuickFiles(scanner);
		scanner.suppressMatchProcessorExceptions(false);
		try
		{
			scanResult = scanner.scan(getThreadCount());
		}
		catch (MatchProcessorException mpe)
		{
			System.out.println(mpe.getExceptions());
		}

**Comment by lukehutch** [comment]
Thanks, modular scanning has not yet been widely tested, so please report any other issues you find. Fixed in 3.1.12.

**Comment by GedMarc** [comment]
![image](https://user-images.githubusercontent.com/5367513/42909618-14e87d12-8ae5-11e8-8f6e-460cc6eb5a58.png)

It's happening on this error :) thanks I'll give it a try now

**Comment by lukehutch** [comment]
Yes, I hadn't tested verbose logging with a modular classpath recently. Module classpath elements don't have an associated File in FCS, since most of the URLs for modules are not valid URLs, they are of the form `jrt:/module.name`. I'm actually surprised that this module of yours does in fact have a valid `file:/` URL, so I'll probably add that to the log as well.
