### ISSUE TITLE
Whitelist doesn't work as expected

### ISSUE THREAD

**Issue by regis-leray** [lukehutch/fast-classpath-scanner#40]
```
List<String> found = new FastClasspathScanner("factories").scan().getNamesOfClassesImplementing("factoryduke.Factory")
```

i'm getting

```
java.lang.IllegalArgumentException: Can't scan for factoryduke.Factory, it is in a package that is either blacklisted or not whitelisted
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.checkClassNameIsInWhitelistedPackage(FastClasspathScanner.java:216)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.annotationName(FastClasspathScanner.java:227)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.getNamesOfClassesWithAnnotation(FastClasspathScanner.java:823)
```

without the package everything is working

```
List<String> found = new FastClasspathScanner().scan().getNamesOfClassesImplementing("factoryduke.Factory")
```

It seems the detection of the whitelist doesnt work well 

```
private static boolean isWhitelisted(final String str, final ArrayList<String> whitelist,
            final ArrayList<String> blacklist) {
        boolean isWhitelisted = false;
        for (final String whitelistPrefix : whitelist) {
            if (str.startsWith(whitelistPrefix)) {
                isWhitelisted = true;
                break;
            }
        }
        boolean isBlacklisted = false;
        for (final String blacklistPrefix : blacklist) {
            if (str.startsWith(blacklistPrefix)) {
                isBlacklisted = true;
                break;
            }
        }
        return isWhitelisted && !isBlacklisted;
    }
```

**Comment by lukehutch** [comment]
Yes, this should have been fixed in version 1.9.17, based on the error message you are using an earlier version.

Can you please update to the latest version and test this again? It should work for the example you gave, but just in case it doesn't work in your case, please let me know so I can investigate further.

**Comment by regis-leray** [comment]
Yes i m using the latest version. 1.9.17

**Comment by regis-leray** [comment]
i can submit a unit test

**Comment by lukehutch** [comment]
Hey, you closed the bug, does that mean it's fixed?

+ That error message changed in 1.9.17, are you sure about the version
you're using?

**Comment by regis-leray** [comment]
@lukehutch thanks, everything is working fine now !

**Comment by lukehutch** [comment]
Great, glad it's working, and thanks for reporting the bug (please report
any other problems you find!).
